### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by djc**
Doesn't yet tackle the rustls 0.22 update (waiting for Quinn) and the hyper 1 update. Should take care of a vulnerability reported against zerocopy < 0.7.31.

### CODE REVIEW

**Comment by bluejekyll** [comment]
probably need to update MSRV as well for one of these.

**Comment by bluejekyll** [comment]
@djc, is this something we still want to get in?

**Review by bluejekyll — CHANGES_REQUESTED** [review]
I think we need to update the MSRV for this.

**Comment by djc** [comment]
Made another iteration that should be able to compile with 1.67.

**Review by bluejekyll — APPROVED** [review]
Looks fine. I’ll let you merge or update the branch as needed.

**Pull request merged**
