### PR TITLE
ci: re-enable Windows

### PR DESCRIPTION
**Pull request by djc**
Blocked on:

- #2589

### CODE REVIEW

**Comment by bluejekyll** [comment]
I think we need to download the new Windows OpenSSL port, or only use rustls?

**Comment by djc** [comment]
> I think we need to download the new Windows OpenSSL port, or only use rustls?

For starters the DNSSEC features need to be detangled so that there's no openssl dependency from the ring features.

**Comment by bluejekyll** [comment]
I think we're still using OpenSSL in some test paths even when only rustls is used.

**Comment by djc** [comment]
Pulling this into #2589.

**Pull request closed without merging**
