### PR TITLE
Bump version to 0.24.1

### PR DESCRIPTION
**Pull request by djc**
This was missing from #2178.

### CODE REVIEW

**Comment by timsutton** [comment]
👋 Hi, I help maintain Homebrew core: would it be possible to re-update the 0.24.1 tag and cut a new GitHub release for it? Asking because I was about to bump the formula version and then found this GH issue :)

**Review by bluejekyll — APPROVED** [review]

**Comment by bluejekyll** [comment]
I think we'll need to delete the 0.24.1 release tag.

**Comment by bluejekyll** [comment]
I'll do that now.

**Comment by faern** [comment]
Thank you for making this release with the fix we needed! :sparkling_heart:

**Pull request merged**
