### PR TITLE
Fork resolv-conf as hickory-resolv-conf

### PR DESCRIPTION
**Pull request by djc**
hickory-resolver depends on resolv-conf for the system resolver configuration (on systems that have `resolv.conf`). Unfortunately there haven't been any commits in 4 years and the maintainer is [unresponsive](https://github.com/tailhook/resolv-conf/issues/36). I propose we start maintaining a fork as part of this repository.

See also:

- #1131
- #1138 

cc @hirschenberger

### CODE REVIEW

**Comment by mokeyish** [comment]
I think it's better to fork a separate repository. Now Hickory DNS is an organization that can accommodate multiple repositories. The advantage of doing this is that you can trace the source and see which changes were made by Hickory DNS and which were made by the original author. It seems that this has rarely been changed over the years, and I think it will also be rarely changed after the bug is fixed. Separate and reduce the amount of code in the main repository.

What do you think?

**Comment by djc** [comment]
Keeping the history connected and keeping it in one repo vs an extra repo are two separate decisions -- we can do an unrelated history merge into this repo, keeping the history connected to any newer commits we make. However, it makes sense to me that we're unlikely to have a very tight integration or much API churn over time, so agreed that a separate repo might make sense.

**Comment by bluejekyll** [comment]
> Unfortunately there haven't been any commits in 4 years and the maintainer is https://github.com/tailhook/resolv-conf/issues/36.

This is unfortunate... That resolv implementation *originated* in this project, and we forked it out at the other maintainers request.

**Review by bluejekyll — APPROVED** [review]

**Comment by bluejekyll** [comment]
I don't have a strong opinion on if it's part of the core set of hickory crates or a separate repo. There is some advantage to having it part of the hickory suite, but the obvious downside is it will be published with versions of hickory even if there are no changes.

**Comment by djc** [comment]
@listochkin managed to contact @tailhook (the current maintainer) and he agreed to give me ownership on crates.io and transferred the repo (back?) to this org. So we can now start moving it forward again.

**Pull request closed without merging**
