### PR TITLE
Update hashbrown

### PR DESCRIPTION
**Pull request by divergentdave**
This updates the version of hashbrown in the lockfile to get off of a yanked version.

### CODE REVIEW

**Review by bluejekyll — APPROVED** [review]
lgtm, thanks for the patch.

**Comment by bluejekyll** [comment]
Looks like this is failing due to https://github.com/rust-fuzz/arbitrary/issues/202

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
> Looks like this is failing due to [rust-fuzz/arbitrary#202](https://github.com/rust-fuzz/arbitrary/issues/202)

Submitted a [fix](https://github.com/rust-fuzz/arbitrary/pull/204) upstream.

**Comment by bluejekyll** [comment]
I'm going to merge this as I don't think we need to worry about past and beta right now...

**Pull request merged**
