### PR TITLE
Prepare 0.24.1

### PR DESCRIPTION
**Pull request by bluejekyll**
@djc and @dlon, this contains the patch for your fix.

should we include anything else? any Cargo.lock updates?

### CODE REVIEW

**Comment by djc** [comment]
You mean this is a backport for #2171, right? @faern was asking about that, not the PR's OP.

**Comment by bluejekyll** [comment]
Yes, I back ported 2171, I think that was the commit that I grabbed.

Let me see about these other changes.

**Comment by bluejekyll** [comment]
Ok, I think this is all correct. ended up cherry-picking everything, but didn't do a great job on the order. Let me know if you think that's a problem, and I can reorder.

**Review by djc — APPROVED** [review]

**Comment by bluejekyll** [comment]
@dlon if you have a moment, could you confirm this has all the changes you require?

**Comment by djc** [comment]
As mentioned before: while dlon started the original PR, @faern was the person asking for a release containing it.

**Comment by dlon** [comment]
@djc @bluejekyll Yep, looks good to me. Thank you!

**Comment by faern** [comment]
Thank you! Looking forward to the release :sparkles:

**Comment by djc** [comment]
@faern @dlon hit a bit of a snag, see #2184 for follow-up.

**Pull request merged**
