### PR TITLE
Revert "authority: parse with default record class IN."

### PR DESCRIPTION
**Pull request by bluejekyll**
Reverts bluejekyll/trust-dns#1874

Sorry, I misunderstood @djc's question in #1874, I'm going to revert and we can continue that conversation.

### CODE REVIEW

**Review by cpu — APPROVED** [review]

**Comment by bluejekyll** [comment]
Sorry for the noise @djc and @cpu, I was a little too quick on reading your responses and didn't notice that it wasn't settled.

**Comment by cpu** [comment]
No trouble at all. Happy to discuss further. :-)

If the alternative approach of removing the parameter is preferred I can open a PR later tonight.

**Comment by djc** [comment]
Reverting isn't really necessary, @cpu can just rebase on top or current main I think? Then you can review and see what you think.

**Comment by bluejekyll** [comment]
Sounds good. You ok with that @cpu?

**Comment by cpu** [comment]
> Sounds good. You ok with that @cpu?

Yup! I will get a PR up for review ASAP.

**Comment by cpu** [comment]
As promised, a PR to remove the argument entirely: https://github.com/bluejekyll/trust-dns/pull/1885 PTAL.

**Pull request closed without merging**
