### PR TITLE
Draft code to add TlsConnect trait

### PR DESCRIPTION
**Pull request by zh-jq-b**
See https://github.com/hickory-dns/hickory-dns/issues/2137

I add a TlsConnect trait in this draft PR, it will be possible for users to use other tls crates to do DoT or DoH.

What do you think about this?

### CODE REVIEW

**Comment by bluejekyll** [comment]
@djc, I think that might be beyond the scope of the motivation for this change? 

@zh-jq-b This seems inline with the existing design I think. At least for the standard socket stuff, this should work. I think there's a lot of complexity with what happens with quic and h3.

**Comment by zh-jq-b** [comment]
> This seems inline with the existing design I think.

Yes, the current rustls/openssl/native-tls feature can be changed to this way, and then DoH can make use of them. I can try to prepare a PR if you think it's acceptable.

> At least for the standard socket stuff, this should work. I think there's a lot of complexity with what happens with quic and h3.

Yes. This can be delayed after the TLS part get resolved.

**Comment by zh-jq-b** [comment]
Close this as OpenSSL is not supported.

**Comment by djc** [comment]
Do you want/need support for OpenSSL? We could have the hooks for what you need if that helps.

**Comment by zh-jq-b** [comment]
> Do you want/need support for OpenSSL?

No, not OpenSSL, we may use [Tongsuo](https://github.com/Tongsuo-Project/Tongsuo) in the future in order to support [TLCP protocol](https://www.chinesestandard.net/PDF/English.aspx/GBT38636-2020).

> We could have the hooks for what you need if that helps.

Thanks. Currently I'm using a simplified version of [client library](https://github.com/bytedance/g3/tree/master/lib/g3-hickory-client) in our code repo with only rustls. I will start a new issue here for discussion when needed.

**Pull request closed without merging**
