### PR TITLE
initial version of the trust-dns book

### PR DESCRIPTION
**Pull request by bluejekyll**
@Darkspirit, I thought you might be interested in this. I considered keeping this out of tree, but decided that it's more valuable to keep in the same repo to discover things might need to be updated in search/find/replace of code.

It's obviously just a layout at the moment, but I'll fill in details as I have time.

### CODE REVIEW

**Comment by bluejekyll** [comment]
here's a serious question, should this book be part of the `trust-dns` repo? or should it be a new repo, that has the trust-dns repo as a submodule?

**Comment by moonshiner** [comment]
I like the submodule idea.  It would allow folks to pull the book and build it separately,

**Comment by bluejekyll** [comment]
oh, actually, I was thinking of doing the opposite: 

`trust-dns-book/trust-dns`

This is to support the building of the internal docs for trust-dns and also host them on the site (for the master branch, released versions are all on docs.rs). It's not really a discovery thing.

**Comment by moonshiner** [comment]
OK, now it becomes clear. totally.

**Comment by bluejekyll** [comment]
Ok, I've pushed the docs all over to here: https://trust-dns.github.io/trust-dns-docs/

**Comment by moonshiner** [comment]
Do you know how hard it was for me to not say "MonoRepo"?

**Comment by bluejekyll** [comment]
Yes. That’s what I realized while i was doing it, and why it’s now in another repo.

**Pull request closed without merging**
